-- Inserir colaboradores do arquivo COLABORADORES_ATIVOS_13.10.2025.xlsx
INSERT INTO registered_voters (email, name) VALUES
('adailton.miranda@sicoob.com.br', 'ADAILTON JOSE MIRANDA'),
('adair.rama@sicoob.com.br', 'ADAIR RAMA'),
('adriana.venites@sicoob.com.br', 'ADRIANA KATIA VENITES'),
('adriane.molinett@sicoob.com.br', 'ADRIANE APARECIDA MOLINETT'),
('adriano.anhaia@sicoob.com.br', 'ADRIANO DIBA ANHAIA'),
('adriele.welter@sicoob.com.br', 'ADRIELE WELTER'),
('adrieli.schell@sicoob.com.br', 'ADRIELI CARLA SCHELL'),
('adriely.martelli@sicoob.com.br', 'ADRIELY ALINE MARTELLI DUTRA'),
('alana.freisleben@sicoob.com.br', 'ALANA FREISLEBEN'),
('alessandra.romero@sicoob.com.br', 'ALESSANDRA APARECIDA ROMERO'),
('alessandra.kanoff@sicoob.com.br', 'ALESSANDRA MARIA KANOFF'),
('alex.bortoluzzi@sicoob.com.br', 'ALEX BORTOLUZZI'),
('aliane.gebing@sicoob.com.br', 'ALIANE TERESINHA GEBING'),
('alice.rodrigues@sicoob.com.br', 'ALICE EDUARDA DE OLIVEIRA RODRIGUES'),
('aliner.trindade@sicoob.com.br', 'ALINE GRASKI SENDERSKI TRINDADE'),
('aline.tedesco@sicoob.com.br', 'ALINE TEDESCO'),
('alinne.franco@sicoob.com.br', 'ALINNE FERREIRA FRANCO'),
('alissond.silva@sicoob.com.br', 'ALISSON DA SILVA'),
('allanf.hartmann@sicoob.com.br', 'ALLAN FRISON HARTMANN'),
('amanda.rosalen@sicoob.com.br', 'AMANDA ROSALEN'),
('ana.mariano@sicoob.com.br', 'ANA BEATRIZ MARIANO'),
('anac.alves@sicoob.com.br', 'ANA CAROLINE ALVES COSTA'),
('ana.asouza@sicoob.com.br', 'ANA PAULA BORGES ALVES DE SOUZA'),
('ana.montes@sicoob.com.br', 'ANA PAULA PAIVA DE OLIVEIRA HAUS MONTES'),
('anderson.cecilio@sicoob.com.br', 'ANDERSON CECILIO'),
('anderson.casagrande@sicoob.com.br', 'ANDERSON FERNANDO CASAGRANDE'),
('andersonh.silveira@sicoob.com.br', 'ANDERSON HAUTRIVE DA SILVEIRA'),
('andre.stupp@sicoob.com.br', 'ANDRE FELIPE KLAUSS STUPP'),
('andrel.costa@sicoob.com.br', 'ANDRE LUIZ SALLES COSTA'),
('andreia.kochhann@sicoob.com.br', 'ANDREIA MIRANDA CORREA KOCHHANN'),
('andressa.stefani@sicoob.com.br', 'ANDRESSA MARIANA STEFANI'),
('andressa.zanelatto@sicoob.com.br', 'ANDRESSA ZANELATTO'),
('andrieli.mena@sicoob.com.br', 'ANDRIELI CHIMENES MENA'),
('angela.cambrussi@sicoob.com.br', 'ANGELA BEDIN CAMBRUSSI'),
('angela.bayer@sicoob.com.br', 'ANGELA GRACIELA TONIAL BAYER'),
('toniob.junior@sicoob.com.br', 'ANTONIO BORDINI JUNIOR'),
('arildo.pirolla@sicoob.com.br', 'ARILDO PIROLLA'),
('arlei.fontanella@sicoob.com.br', 'ARLEI FONTANELLA'),
('brendam.santos@sicoob.com.br', 'BRENDA MARTINELLI SANTOS'),
('bruna.bampi@sicoob.com.br', 'BRUNA EDUARDA LUDVICHAK BAMPI'),
('camila.barea@sicoob.com.br', 'CAMILA BAREA'),
('camila.sribeiro@sicoob.com.br', 'CAMILA DA SILVA RIBEIRO'),
('camila.fcosta@sicoob.com.br', 'CAMILA FERNANDES DA COSTA'),
('camilaf.mello@sicoob.com.br', 'CAMILA FRANCIELE DE MELLO'),
('carina.salapata@sicoob.com.br', 'CARINA NERY DA SILVA SALAPATA'),
('carla.gral@sicoob.com.br', 'CARLA APARECIDA PAZINI GRAL'),
('carla.moraes@sicoob.com.br', 'CARLA DE OLIVEIRA DE MORAES'),
('carline.silva@sicoob.com.br', 'CARLINE LOURDES DA SILVA'),
('carlos.arodrigues@sicoob.com.br', 'CARLOS ALBERTO RODRIGUES'),
('carolaine.aparecida@sicoob.com.br', 'CAROLAINE APARECIDA MARQUES ROTTA'),
('caroline.feix@sicoob.com.br', 'CAROLINE FEIX'),
('caroline.sella@sicoob.com.br', 'CAROLINE SIGNORINI SELLA'),
('caroline.spenazzatto@sicoob.com.br', 'CAROLINE XAVIER DA SILVA SPENAZZATTO'),
('cassiane.pesente@sicoob.com.br', 'CASSIANE RECK PESENTE'),
('catiane.santos@sicoob.com.br', 'CATIANE APARECIDA COSTA DOS SANTOS'),
('cezar.neves@sicoob.com.br', 'CEZAR AUGUSTO ROSA NEVES'),
('clailton.lopes@sicoob.com.br', 'CLAILTON ANDRE LOPES'),
('claudia.severino@sicoob.com.br', 'CLAUDIA CARNEIRO SEVERINO'),
('claudiag.costa@sicoob.com.br', 'CLAUDIA GONCALVES DA COSTA'),
('claudinei.cruz@sicoob.com.br', 'CLAUDINEI RODRIGUES DA CRUZ'),
('cleberson.davies@sicoob.com.br', 'CLEBERSON ALEX DAVIES'),
('cleberson.pereira@sicoob.com.br', 'CLEBERSON PEREIRA'),
('cliff.stanga@sicoob.com.br', 'CLIFF ANDERSON STANGA'),
('cristiane.calgaro@sicoob.com.br', 'CRISTIANE CALGARO'),
('cristiano.marostega@sicoob.com.br', 'CRISTIANO ANTONIO MAROSTEGA'),
('cristiano.cruz@sicoob.com.br', 'CRISTIANO DA SILVA CRUZ'),
('cristina.almeida@sicoob.com.br', 'CRISTINA ALMEIDA'),
('daiana.cari@sicoob.com.br', 'DAIANA DA FONSECA CARI'),
('daiane.girelli@sicoob.com.br', 'DAIANE APARECIDA GRANDO GIRELLI'),
('daiane.terres@sicoob.com.br', 'DAIANE ROCHER TERRES'),
('daniela.defante@sicoob.com.br', 'DANIELA DEFANTE NAGLIATE'),
('daniela.borghelot@sicoob.com.br', 'DANIELA LUIZA BORGHELOT'),
('daniele.harka@sicoob.com.br', 'DANIELE HARKA'),
('danielio.cordeiro@sicoob.com.br', 'DANIELI DE OLIVEIRA CORDEIRO'),
('danieli.roginski@sicoob.com.br', 'DANIELI LUANA ROGINSKI'),
('daniely.novak@sicoob.com.br', 'DANIELY CONSTANTE NOVAK'),
('dayane.pothin@sicoob.com.br', 'DAYANE CRISTINA POTHIN MACEDO'),
('dayani.souza@sicoob.com.br', 'DAYANI GOMES DE SOUZA'),
('debora.mealho@sicoob.com.br', 'DEBORA KARLENE MEALHO'),
('deivid.laskoski@sicoob.com.br', 'DEIVID VINICIUS LASKOSKI'),
('dejiane.silva@sicoob.com.br', 'DEJIANE DA SILVA'),
('denised.ramos@sicoob.com.br', 'DENISE DE SISTO NAIA RAMOS'),
('denise.moretto@sicoob.com.br', 'DENISE DELUCAS MORETTO'),
('dheniffer.pasa@sicoob.com.br', 'DHENIFFER PASA MARCOLIN'),
('diegoc.camargo@sicoob.com.br', 'DIEGO CAMARGO'),
('dieimi.vendrametto@sicoob.com.br', 'DIEIMI SUELEN DE LIMA VENDRAMETTO'),
('edimara.batista@sicoob.com.br', 'EDIMARA LOCATELLI BATISTA'),
('edsonm.maximo@sicoob.com.br', 'EDSON MAXIMO'),
('eduarda.bronstrup@sicoob.com.br', 'EDUARDA CAROLINE KUNZLER BRONSTRUP'),
('eduardo.tironi@sicoob.com.br', 'EDUARDO CEZAR TIRONI'),
('eduardo.stein@sicoob.com.br', 'EDUARDO FELLIPPE STEIN'),
('eduardo.rodrigues@sicoob.com.br', 'EDUARDO FRANCISCO SIEJKA RODRIGUES'),
('elaine.stein@sicoob.com.br', 'ELAINE MARIA STEIN'),
('eliane.rsilva@sicoob.com.br', 'ELIANE ROSINEIA DA SILVA VIDOTTI'),
('elizane.gracas@sicoob.com.br', 'ELIZANE FLAVIA DAS GRACAS'),
('eloi.almeida@sicoob.com.br', 'ELOI DE ALMEIDA'),
('emanuele.jesus@sicoob.com.br', 'EMANUELE MARIA GRACIOLI DE JESUS'),
('emanuelle.barbosa@sicoob.com.br', 'EMANUELLE CAROLINE OLIVEIRA BARBOSA'),
('emily.siejka@sicoob.com.br', 'EMILY FERNANDA MOLON SIEJKA'),
('enidia.pietrobom@sicoob.com.br', 'ENIDIA PERETTI PIETROBOM'),
('erico.schulz@sicoob.com.br', 'ERICO EMILIO SCHULZ'),
('fabiod.silveira@sicoob.com.br', 'FABIO DARIO SILVEIRA'),
('fabio.reck@sicoob.com.br', 'FABIO HENRIQUE RECK'),
('felipep.bernardi@sicoob.com.br', 'FELIPE PIENTOSA BERNARDI'),
('fernanda.rovere@sicoob.com.br', 'FERNANDA DE ANDRADE DAL ROVERE'),
('fernando.john@sicoob.com.br', 'FERNANDO LUCAS JOHN'),
('fernando.canedo@sicoob.com.br', 'FERNANDO RIBEIRO CANEDO'),
('flavio.santos@sicoob.com.br', 'FLAVIO PROVENSI DOS SANTOS'),
('francieli.silveira@sicoob.com.br', 'FRANCIELI MALLMANN SILVEIRA'),
('gabrielf.franca@sicoob.com.br', 'GABRIEL FELIPE TECCKIO DE FRANCA'),
('gabriel.carminati@sicoob.com.br', 'GABRIEL PEDRO ALBIAZZETTI CARMINATI'),
('gabriela.cristo@sicoob.com.br', 'GABRIELA AFONSO DE CRISTO HUTNER'),
('gabriela.devens@sicoob.com.br', 'GABRIELA DE MELO DEVENS'),
('gabrielle.cheredra@sicoob.com.br', 'GABRIELLE CHEREDRA'),
('gabrielli.buzinaro@sicoob.com.br', 'GABRIELLI PALUDO BUZINARO'),
('geovana.carvalho@sicoob.com.br', 'GEOVANA RABELO DE CARVALHO'),
('gessica.bez@sicoob.com.br', 'GESSICA JULIANA BEZ'),
('gessica.mazzardo@sicoob.com.br', 'GESSICA TEREZA SIMIONATO MAZZARDO'),
('giovana.donato@sicoob.com.br', 'GIOVANA DONATO'),
('gisela.tasca@sicoob.com.br', 'GISELA PAULA TASCA'),
('giseled.santos@sicoob.com.br', 'GISELE DOS SANTOS'),
('giulie.lorente@sicoob.com.br', 'GIULIE KRISTIE RODRIGES LORENTE'),
('gracy.souza@sicoob.com.br', 'GRACY KELLY FREITAS DE SOUZA'),
('graziele.bento@sicoob.com.br', 'GRAZIELE BENTO'),
('guilherme.zampieri@sicoob.com.br', 'GUILHERME CASARIM ZAMPIERI'),
('heloiza.chimim@sicoob.com.br', 'HELOIZA CHIMIM'),
('hercules.sondei@sicoob.com.br', 'HERCULES DILGER SONDEI'),
('hevilin.oliveira@sicoob.com.br', 'HEVILIN THAMARA GEMPKA DE OLIVEIRA'),
('higor.morais@sicoob.com.br', 'HIGOR PINTO MORAIS'),
('ildemar.ceron@sicoob.com.br', 'ILDEMAR CERON'),
('indiamara.araujo@sicoob.com.br', 'INDIAMARA CINTIA MACHADO DE ARAUJO'),
('isabela.soares@sicoob.com.br', 'ISABELA SOARES'),
('isabellac.silveira@sicoob.com.br', 'ISABELLA CASAGRANDE SILVEIRA'),
('isabella.lago@sicoob.com.br', 'ISABELLA DE SOUZA LAGO'),
('ivo.caregnato@sicoob.com.br', 'IVO JOSE CAREGNATO JUNIOR'),
('izolete.fank@sicoob.com.br', 'IZOLETE FERNANDES FANK'),
('jaime.gonzatto@sicoob.com.br', 'JAIME CESAR GONZATTO'),
('jaine.neiss@sicoob.com.br', 'JAINE BUCHINGER NEISS'),
('jaqueline.pelegrin@sicoob.com.br', 'JAQUELINE DE SOUZA ALTHAUS PELEGRIN'),
('jaquiele.demarchi@sicoob.com.br', 'JAQUIELE DEMARCHI'),
('jean.asilva@sicoob.com.br', 'JEAN APARECIDO DA SILVA'),
('jenifer.ferrari@sicoob.com.br', 'JENIFER FERRARI'),
('jennyfer.reis@sicoob.com.br', 'JENNYFER PADILHA REIS'),
('jeorgia.mozel@sicoob.com.br', 'JEORGIA DRIELI MOZEL'),
('jessica.ossovski@sicoob.com.br', 'JESSICA OSSOVSKI'),
('jessica.tsantos@sicoob.com.br', 'JESSICA TABALIPA SANTOS'),
('jhuan.zanoni@sicoob.com.br', 'JHUAN PAULO ZANONI'),
('joaog.candido@sicoob.com.br', 'JOAO GUILHERME CANDIDO'),
('joao.antoniolli@sicoob.com.br', 'JOAO PEDRO ANTONIOLLI'),
('joao.braz@sicoob.com.br', 'JOAO VITOR BRAZ DOS SANTOS'),
('jociane.teixeira@sicoob.com.br', 'JOCIANE LISBOA TEIXEIRA'),
('jorge.ambrosi@sicoob.com.br', 'JORGE LUIS LIMA AMBROSI'),
('jose.valente@sicoob.com.br', 'JOSE HENRIQUE VALENTE'),
('joseleny.piasecki@sicoob.com.br', 'JOSELENY CARLA PIASECKI'),
('jucilaine.sanches@sicoob.com.br', 'JUCILAINE DE CARLI SANCHES'),
('juliana.gregio@sicoob.com.br', 'JULIANA APARECIDA GREGIO'),
('juliana.pedrotti@sicoob.com.br', 'JULIANA PEDROTTI'),
('juliano.rraimundo@sicoob.com.br', 'JULIANO RICARDO RAIMUNDO'),
('juliano.osorio@sicoob.com.br', 'JULIANO ROTAVA OSORIO'),
('jussani.vidal@sicoob.com.br', 'JUSSANI VIDAL'),
('karina.fassina@sicoob.com.br', 'KARINA DOS REIS FASSINA'),
('karine.jsantos@sicoob.com.br', 'KARINE JUNG RODRIGUES DOS SANTOS'),
('karyn.silva@sicoob.com.br', 'KARYN SCHROEDER SOKOLOWSKI SILVA'),
('kauanyw.santos@sicoob.com.br', 'KAUANY WISNIEWSKI DOS SANTOS'),
('keli.lautert@sicoob.com.br', 'KELI CRISTINE LAUTERT'),
('kelida.almeida@sicoob.com.br', 'KELIDA MELISSA DE ALMEIDA'),
('kelli.nicoski@sicoob.com.br', 'KELLI CRISTINA FERREIRA NICOSKI'),
('kelli.ligoski@sicoob.com.br', 'KELLI CRISTINA LIGOSKI'),
('kelli.rossetto@sicoob.com.br', 'KELLI CRISTINA MACHADO ROSSETTO'),
('kessy.nieratka@sicoob.com.br', 'KESSY ELLEN NIERATKA'),
('keverson.horinouti@sicoob.com.br', 'KEVERSON HUDNER HORINOUTI'),
('khaiany.ker@sicoob.com.br', 'KHAIANY PEREIRA KER'),
('khetlin.silva@sicoob.com.br', 'KHETLIN ELOISI DA SILVA'),
('kimberli.oliveira@sicoob.com.br', 'KIMBERLI YARIN DE OLIVEIRA'),
('kleber.lima@sicoob.com.br', 'KLEBER GUSTAVO LIMA'),
('lais.hoffmann@sicoob.com.br', 'LAIS SAMARA DIAS HOFFMANN'),
('lauriane.silva@sicoob.com.br', 'LAURIANE MAYARA SCHMOELLER DA SILVA'),
('leticia.drosa@sicoob.com.br', 'LETICIA DA ROSA'),
('leticia.svieira@sicoob.com.br', 'LETICIA DA SILVA VIEIRA'),
('leticial.ferreira@sicoob.com.br', 'LETICIA LOURENCO FERREIRA DA SILVA'),
('leticia.ramos@sicoob.com.br', 'LETICIA NAYRA RAMOS'),
('lizielle.alvarenga@sicoob.com.br', 'LIZIELLE GONZATTO ALVARENGA'),
('luan.pietroski@sicoob.com.br', 'LUAN GUSTAVO SOUZA PIETROSKI'),
('luan.lara@sicoob.com.br', 'LUAN MARCOS MOREIRA LARA'),
('luanam.goncalves@sicoob.com.br', 'LUANA MAIA GONCALVES'),
('luanam.venzon@sicoob.com.br', 'LUANA MARTINS VENZON'),
('luana.sadovnhic@sicoob.com.br', 'LUANA SADOVNHIC'),
('lucast.silva@sicoob.com.br', 'LUCAS ANTONIO VARGAS DA SILVA'),
('lucas.viola@sicoob.com.br', 'LUCAS RAFAEL VIOLA'),
('lucimara.machado@sicoob.com.br', 'LUCIMARA MACHADO'),
('lucineia.zorzetto@sicoob.com.br', 'LUCINEIA APARECIDA ZORZETTO'),
('luis.novossado@sicoob.com.br', 'LUIS HENRIQUE POLIDORO NOVOSSADO'),
('luiz.almeida@sicoob.com.br', 'LUIZ EDERSON DE ALMEIDA'),
('luiz.spacki@sicoob.com.br', 'LUIZ FELIPE BARBOSA SPACKI'),
('luiz.dybas@sicoob.com.br', 'LUIZ FELIPE DYBAS'),
('luiza.carard@sicoob.com.br', 'LUIZA CRISTINA CITON CARARD'),
('marcelao.santos@sicoob.com.br', 'MARCELA OLIVEIRA SANTOS'),
('marcia.vetorello@sicoob.com.br', 'MARCIA DE FATIMA GAVLIK VETORELLO'),
('marcia.cantelli@sicoob.com.br', 'MARCIA MATOS DA SILVA CANTELLI'),
('marciele.renata@sicoob.com.br', 'MARCIELE RENATA LOPES'),
('marian.silva@sicoob.com.br', 'MARIA ALICE DANTAS DA SILVA'),
('maria.petry@sicoob.com.br', 'MARIA EDUARDA PETRY'),
('maria.reolon@sicoob.com.br', 'MARIA EDUARDA REOLON'),
('maria.spohn@sicoob.com.br', 'MARIA EDUARDA SPOHN'),
('mariaf.carvalho@sicoob.com.br', 'MARIA FERNANDA RABELO DE CARVALHO'),
('maria.kmiecik@sicoob.com.br', 'MARIA GABRIELE KMIECIK'),
('mariete.chimelo@sicoob.com.br', 'MARIETE CHIMELO'),
('marilaque.anzolin@sicoob.com.br', 'MARILAQUE APARECIDA ISRAEL ANZOLIN'),
('marina.vargas@sicoob.com.br', 'MARINA PAULA DE VARGAS'),
('martham.dams@sicoob.com.br', 'MARTHA MARIA KARACHINSKI DAMS'),
('matheus.cassol@sicoob.com.br', 'MATHEUS AUGUSTO CASSOL'),
('matteus.florencio@sicoob.com.br', 'MATTEUS JEZREEL QUARENTEI FLORENCIO'),
('mauricio.peixe@sicoob.com.br', 'MAURICIO PEIXE MACIEL'),
('mayan.borille@sicoob.com.br', 'MAYAN CRISTINA RODRIGUES BORILLE'),
('mayanne.melo@sicoob.com.br', 'MAYANNE FERNANDES DE MELO'),
('mayaras.freitas@sicoob.com.br', 'MAYARA SILVA FREITAS'),
('mayara.tlima@sicoob.com.br', 'MAYARA TAVANA SCHEFFLER DE LIMA'),
('mery.garmus@sicoob.com.br', 'MERY TEREZINHA RAISKI GARMUS'),
('micheld.santos@sicoob.com.br', 'MICHEL DOS SANTOS'),
('michelly.pasqualotto@sicoob.com.br', 'MICHELLY PASQUALOTTO'),
('milena.becker@sicoob.com.br', 'MILENA BECKER'),
('monical.aires@sicoob.com.br', 'MONICA LUCCA AIRES'),
('natan.gabriel@sicoob.com.br', 'NATAN GABRIEL SCALVENCE ANDRADE'),
('natanac.periolo@sicoob.com.br', 'NATANA CAMILA PRASS PERIOLO'),
('nathaliat.santos@sicoob.com.br', 'NATHALIA TOME DOS SANTOS'),
('natielli.john@sicoob.com.br', 'NATIELLI CRISTINA JOHN'),
('oneide.abbady@sicoob.com.br', 'ONEIDE DA SILVA ABBADY'),
('osmair.nascimento@sicoob.com.br', 'OSMAIR VITALINO DO NASCIMENTO'),
('patricia.alberton@sicoob.com.br', 'PATRICIA ALBERTON'),
('patricia.aribeiro@sicoob.com.br', 'PATRICIA APARECIDA DE ARAUJO RIBEIRO'),
('patricia.cristo@sicoob.com.br', 'PATRICIA KAILER DE CRISTO'),
('patricia.girelli@sicoob.com.br', 'PATRICIA LUCIA LINZMEYER GIRELLI'),
('patricia.doliveira@sicoob.com.br', 'PATRICIA SANTOS DE OLIVEIRA'),
('patrick.oliveira@sicoob.com.br', 'PATRICK FONGARO DE OLIVEIRA'),
('paula.unser@sicoob.com.br', 'PAULA BARTSCH UNSER'),
('paula.rafagnin@sicoob.com.br', 'PAULA CRISTINA RAFAGNIN'),
('pedrof.junior@sicoob.com.br', 'PEDRO FERRARINI JUNIOR'),
('pollyana.lima@sicoob.com.br', 'POLLYANA ANDRESSA WILKE IANSEN'),
('priscila.bonemberger@sicoob.com.br', 'PRISCILA BONEMBERGER'),
('rafael.freitas@sicoob.com.br', 'RAFAEL FERNANDO FREITAS'),
('rafael.galera@sicoob.com.br', 'RAFAEL GALERA'),
('rafael.quagliotto@sicoob.com.br', 'RAFAEL GUELES QUAGLIOTTO'),
('rafael.locatelli@sicoob.com.br', 'RAFAEL LOCATELLI'),
('rafaela.bellon@sicoob.com.br', 'RAFAELA BELLON'),
('renata.bartnik@sicoob.com.br', 'RENATA FRANCIELE BARTNIK'),
('renata.sotti@sicoob.com.br', 'RENATA WINCK SOTTI'),
('ricardo.andre@sicoob.com.br', 'RICARDO ANDRE DOS SANTOS'),
('robert.santos@sicoob.com.br', 'ROBERT RIVALDO MARTINS DOS SANTOS'),
('roberta.caltran@sicoob.com.br', 'ROBERTA DIAS CALTRAN'),
('robertas.lima@sicoob.com.br', 'ROBERTA SANTOS LIMA'),
('robson.bittencourt@sicoob.com.br', 'ROBSON HENRIQUE BITTENCOURT'),
('rosely.tremea@sicoob.com.br', 'ROSELY FATIMA TREMEA'),
('rosemeri.hartmann@sicoob.com.br', 'ROSEMERI HARTMANN'),
('rosimar.passaglia@sicoob.com.br', 'ROSIMAR JOSE PASSAGLIA'),
('rosinei.carvalho@sicoob.com.br', 'ROSINEI ROSA DE CARVALHO'),
('samanta.oliveira@sicoob.com.br', 'SAMANTA CALINE RESENDE DE OLIVEIRA'),
('schermen.dias@sicoob.com.br', 'SCHERMEN DE PAULA DIAS'),
('silvana.rosseti@sicoob.com.br', 'SILVANA ROSSETI'),
('silvia.nishiyama@sicoob.com.br', 'SILVIA NAOMI KINOSHITA NISHIYAMA'),
('simoni.passos@sicoob.com.br', 'SIMONI CRISTINA DOS PASSOS'),
('sthefanny.moro@sicoob.com.br', 'STHEFANNY DAL MORO ZIELKE'),
('suziane.somariva@sicoob.com.br', 'SUZIANE APARECIDA SOMARIVA'),
('talita.estevam@sicoob.com.br', 'TALITA TAVARES DE MACEDO SILVA ESTEVAM'),
('tassima.berto@sicoob.com.br', 'TASSIMA MORENI BERTO'),
('tauandra.figueiro@sicoob.com.br', 'TAUANDRA DOS SANTOS FIGUEIRO'),
('thais.hsouza@sicoob.com.br', 'THAIS HEVELIN FAPPI DE SOUZA'),
('thayna.fernandes@sicoob.com.br', 'THAYNA VARGAS FERNANDES'),
('thiago.rambaldi@sicoob.com.br', 'THIAGO FELIPE GAZOLI RAMBALDI'),
('thiego.sobczak@sicoob.com.br', 'THIEGO SECCHI SOBCZAK'),
('vanessa.doliveira@sicoob.com.br', 'VANESSA DE OLIVEIRA'),
('vanessa.malaguti@sicoob.com.br', 'VANESSA MALAGUTI'),
('vera.nogueira@sicoob.com.br', 'VERA LUCIA NOGUEIRA'),
('veridiana.mschu@sicoob.com.br', 'VERIDIANA MARCANTE SCHU'),
('vitor.miola@sicoob.com.br', 'VITOR MATHEUS MIOLA'),
('wemeli.cristina@sicoob.com.br', 'WEMELI CRISTINA CAMARGO DE TOLEDO'),
('wolmir.flores@sicoob.com.br', 'WOLMIR RIBEIRO FLORES'),
('01@pluricoop.com.br', 'TESTE 1'),
('02@pluricoop.com.br', 'TESTE 2'),
('03@pluricoop.com.br', 'TESTE 3'),
('04@pluricoop.com.br', 'TESTE 4'),
('05@pluricoop.com.br', 'TESTE 5'),
('06@pluricoop.com.br', 'TESTE 6'),
('07@pluricoop.com.br', 'TESTE 7'),
('08@pluricoop.com.br', 'TESTE 8'),
('09@pluricoop.com.br', 'TESTE 9'),
('10@pluricoop.com.br', 'TESTE 10'),
('11@pluricoop.com.br', 'TESTE 11'),
('12@pluricoop.com.br', 'TESTE 12'),
('13@pluricoop.com.br', 'TESTE 13'),
('14@pluricoop.com.br', 'TESTE 14'),
('15@pluricoop.com.br', 'TESTE 15')
ON CONFLICT (email) DO NOTHING;