// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glwywowbhawpmaatpvdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsd3l3b3diaGF3cG1hYXRwdmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NzY2MzUsImV4cCI6MjA1MTI1MjYzNX0.wwNBNq5ihE8zCFnlAlHFeZTebiHlVTEsJtiPd4qMtic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);